### ISSUE TITLE
在tooltip弹出的面板中再使用tooltip时，会触发面板hide

### ISSUE THREAD

**Issue by paseo** [uxcore/uxcore-tooltip#3]
在tooltip的hover模式下，在弹出的面板中包含其他带picker的组件。即使将picker渲染到tooltip弹出的内容dom中，也会触发tooltip的onMouseLeave事件

**Comment by eternalsky** [comment]
fix in https://github.com/react-component/trigger/commit/14c2b3858601233b99d2e0f8404f9adbd7443a33
